project:
  type: website

website:
  title: "Patoloji Atlası"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tipfakultesi.qmd
      - gastro.qmd
      - genital.qmd
      - uriner.qmd
      - jineko.qmd
      - meme.qmd
      - referanslar.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    light: flatly
    dark: darkly
    code-fold: true
    code-tools: true
    fig-width: 8
    fig-height: 4
    execute:
      warning: false
    self-contained: false
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.patolojiatlasi\.com\/'
    citations-hover: true
    footnotes-hover: true
  pdf: default
  epub: default

bibliography: references.bib

editor: visual

